name: tiktok_downloader_ui
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  archive: ^4.0.4  # Updated to latest compatible version
  permission_handler: ^11.0.1
  file_picker: ^9.0.2
  dio: ^5.4.0
  path_provider: ^2.1.5
  flutter_local_notifications: ^18.0.1
  workmanager: ^0.5.1
  async: ^2.12.0
  material_color_utilities: ^0.11.1  # Updated version
  fake_async: ^1.3.2  # Match the version required by flutter_test
  leak_tracker: ^10.0.8  # Match the version required by flutter_test
  vm_service: 14.3.1  # Match the version required by flutter_test
  cupertino_icons: ^1.0.8
  flutter_launcher_icons: ^0.14.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  http: ^0.13.6
  video_player: ^2.9.3
  photo_manager: ^3.6.4
  gallery_saver: ^2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.14  # Updated version
  hive_generator: ^2.0.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/TTDLAppIcon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/
